version: 2
jobs: 
  build: 
    docker: 
      - image: "circleci/node:10-browsers"
    working_directory: ~/project-name
    steps: 
      - checkout
      - run: 
          command: "echo ${CIRCLE_BRANCH}"
          name: "Show current branch"
      - restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package-lock.json\" }}"
            - v1-dependencies-
      - run: 
          command: "npm install"
          name: "Install local dependencies"
      - save_cache: 
          key: "v1-dependencies-{{ checksum \"package-lock.json\" }}"
          paths: 
            - node_modules
      - run: 
          command: "npm run lint"
          name: Linting
      - run: 
          command: "npm run test --"
          name: Testing
      - run: 
          command: "npm run e2e --"
          name: "End to End Test"
